### ISSUE TITLE
da14531 use case Central, Add uart1 to this routine. uart1 crashes while receiving data

### ISSUE THREAD

**Issue by 919643218** [dialog-semiconductor/BLE_SDK6_examples#118]
I am using the routine https://github.com/dialog-semiconductor/BLE_SDK6_examples/tree/main/connectivity/central and added uart1 to the routine to send and receive custom data to and from the test pc. But when I send data from pc to da14531, da14531 crashes. da14531 sends data to pc and it's fine again! Running the uart routines in the sdk alone. Sending and receiving is fine
![pastedimage1713408848560v1 png-640x480](https://github.com/dialog-semiconductor/BLE_SDK6_examples/assets/46235895/9d16872c-690e-465a-aad8-459483d18cd1)
![pastedimage1713408866619v2 png-640x480](https://github.com/dialog-semiconductor/BLE_SDK6_examples/assets/46235895/9a0e39e0-2a03-498b-b37f-ad6286e05870)
![pastedimage1713408891019v3 png-640x480](https://github.com/dialog-semiconductor/BLE_SDK6_examples/assets/46235895/0a92d4d1-8386-4d6e-bbb9-d4d75eedbc01)
![pastedimage1713408904883v4 png-640x480](https://github.com/dialog-semiconductor/BLE_SDK6_examples/assets/46235895/242ca4d9-892a-4771-9ca5-879a576c1286)
![pastedimage1713408916788v5 png-640x480](https://github.com/dialog-semiconductor/BLE_SDK6_examples/assets/46235895/27ea7a21-93ed-420f-8917-f7e28676c837)

**Comment by massimilian-89** [comment]
Please clone the latest version.
