### ISSUE TITLE
Linker Errors

### ISSUE THREAD

**Issue by YudiRRNZ** [dialog-semiconductor/BLE_SDK6_examples#119]
Hi all, 

I followed the instructions to link the examples to the main sdk I downloaded but when I build the project I get the following linker errors:
`linking...
.\out_DA14531\Objects\central_531.axf: Error: L6218E: Undefined symbol my_custom_msg_handlers (referred from arch_rom.o).
.\out_DA14531\Objects\central_531.axf: Error: L6218E: Undefined symbol patch_func (referred from user_periph_setup.o).
.\out_DA14531\Objects\central_531.axf: Error: L6218E: Undefined symbol lld_force_timeout_refresh (referred from patch_1.o).
Not enough information to produce a SYMDEFs file.
Not enough information to list image symbols.
Not enough information to list load addresses in the image map.
Finished: 3 information, 0 warning and 3 error messages.
".\out_DA14531\Objects\central_531.axf" - 3 Error(s), 0 Warning(s).
Target not created.
Build Time Elapsed:  00:00:09`

What can I do to fix this? I am using the SDK6.0.22 and a DA14531 Devboard pro kit

Edit1: I am trying to build and run the Central project under connectivity

**Comment by massimilian-89** [comment]
Hello

Our SDK6_examples repository is right in Update process for the new SDK6 version. Meanwhile, I can share with you the central example. Please remember from this version, DO NOT use the python script for linking anymore and try to clone the examples inside the project folder directly. If you need other example sooner let me know. 
[6.0.20.1338_DA14535_Central.zip](https://github.com/dialog-semiconductor/BLE_SDK6_examples/files/15414188/6.0.20.1338_DA14535_Central.zip)

Best Reagrds 
Moh
