### ISSUE TITLE
error compiling multi_con_periph project

### ISSUE THREAD

**Issue by sachinjairam** [dialog-semiconductor/BLE_SDK6_examples#86]
Hi,
 I have compiled the multi_con_periph project for DA14531 and got the error:

![image](https://user-images.githubusercontent.com/44083276/229278118-dd5dcbc1-6afb-4c96-a856-debf09431b34.png)

I have linked the project with SDK version 6.0.14 using the python script and it was successful. 
How can I resolve the issue?

**Comment by massimilian-89** [comment]
Hello 
Our examples now are compatible with ARM compiler V6 and the latest version of SDK6. I suggest downloading the latest version of SDK6 from:

https://www.renesas.com/us/en/document/swo/sdk601811821-da1453x-da145856?r=1564826

Other than this, please take this to your consideration that this example needs some modifications in SDK files which have been described in the Readme.
Best Regards

**Comment by sachinjairam** [comment]
@massimilian-89 Thanks for the reply.
I have updated my SDK  and compiler and it's worked.
