### ISSUE TITLE
CI banner generator ignores intended targets

### ISSUE THREAD

**Issue by koen-vdm** [dialog-semiconductor/BLE_SDK6_examples#92]
The CI tools merged in #89 do not look at the intended targets when generating the shields banner. So if a project in made for only the DA14531, the banner also shows DA14585 and DA14586. The additional targets are however set to inactive (greyed out). This was noticed by @ibenamor in this project: https://github.com/dialog-semiconductor/BLE_SDK6_examples/tree/main/connectivity/Quuppa_DialogTag.

**Comment by koen-vdm** [comment]
@blauret, I vaguely remember that also displaying the targets for which the project is not intended was your idea. But I might be wrong. What do you think?

**Comment by blauret** [comment]
I think it's fine as it is.
