### ISSUE TITLE
CMake run

### ISSUE THREAD

**Issue by morozovars** [dialog-semiconductor/BLE_SDK6_examples#93]
Hello how to build examples using cmake?

**Comment by koen-vdm** [comment]
Hello @morozovars,

To buid examples using cmake, you have to first make sure you have the tools installed on linux:
`apt update && apt install -y git cmake build-essential gcc-arm-none-eabi unzip`

Then you have to download the SDK from here (and unzip it): 
- https://www.renesas.com/us/en/document/swo/sdk601811821-da1453x-da145856?r=1564826

And then you need to generate the build files by executing the following command inside the direcrtory of the project you want to build:
`cmake -DDEVICE_NAME=name -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_TOOLCHAIN_FILE=/path/to/the/cloned/repo/build_utils/gcc/arm-none-eabi.cmake -DGCC_TOOLCHAIN_PATH=/usr/bin/arm-none-eabi -DDIALOG_SDK_PATH=/path/to/downloaded/sdk/DA145xx_SDK/6.0.18.1182.1 -DDIALOG_EXAMPLE_PATH=/path/to/cloned/repo -S . -B ./build` 
Be sure to rename the paths according to your setup.

build the project using:
`cd build && make`
The .bin file should be in ./build/projectname_target.bin

Please be aware that not all of our projects build using cmake (with the gcc compiler). you can check the build status using the colored labels in the respective readme, green label means it build.

Hope this helps!
